---
- name: Master WinSrv2016 Task List
  hosts: winsrv_purple
  tasks:

  - name: Uninstall Windows Defender
    win_shell: Uninstall-WindowsFeature -Name Windows-Defender

  - name: Reboot
    win_reboot:


